enabled: true

storage-type: "mariadb"

# Set MariaDB connection details
# Table name is "verifications"
storage:
  host: "localhost:3306"
  user: "root"
  pass: ""
  database: "minecraft"

# Verified group name
verified-group: "verified"

# Verification url
url: "https://mc.gimb.tk/verify/"